[paperless]
enabled  = true
maxretry = 5
filter   = paperless
logpath  = /home/nonroot/paperless/data/log/paperless.log 
chain    = DOCKER-USER
port     = 8000
[paperless_proxy]
enabled  = true
maxretry = 5
filter   = paperless
logpath  = /home/nonroot/paperless/data/log/paperless.log 
port     = http,https
